version: '3.8'

services:
    database:
        image: mariadb:11
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: password
        
    redis:
        image: redis:alpine
        restart: always

    nextcloud:
        image: nextcloud
        ports:
            - 8080:80
        restart: always
        volumes:
            - nextcloud_data:/var/www/html
        environment:
            MYSQL_HOST: database
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: password
            REDIS_HOST: redis
        depends_on:
            - database
            - redis

volumes:
    db_data:
    nextcloud_data:



